import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserInfo } from "@/components/userInfo/UserInfo";
import { StoreWrapper } from "@/components/storeWrapper/StoreWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreWrapper>
          <UserInfo />
          <main className="wrapper">{children}</main>
        </StoreWrapper>
      </body>
    </html>
  );
}
